### ISSUE TITLE
Build occasionally hangs on postgresql-maven-plugin

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-jdbc#13]
Run `mvn clean install -Pqulice`. Sometimes it works, sometimes it just hangs at the message below. May be environment specific - I'm running Win7. 
```
[INFO] This user must also own the server process.
[INFO]
[INFO] The database cluster will be initialized with locale "English_United States.1252".
[INFO] The default database encoding has accordingly been set to "WIN1252".
[INFO] The default text search configuration will be set to "english".
[INFO]
[INFO] creating directory C:/Users/Carlos Miranda/git/jcabi-jdbc/target/data ... ok
[INFO] creating subdirectories ... ok
[INFO] selecting default max_connections ... 100
[INFO] selecting default shared_buffers ... 32MB
[INFO] creating configuration files ... ok
[INFO] creating template1 database in C:/Users/Carlos Miranda/git/jcabi-jdbc/target/data/base/1 ... ok
[INFO] initializing pg_authid ... ok
[INFO] setting password ... ok
[INFO] initializing dependencies ... ok
[INFO] creating system views ... ok
[INFO] loading system objects' descriptions ... ok
[INFO] creating collations ... not supported on this platform
[INFO] creating conversions ... ok
[INFO] creating dictionaries ... ok
[INFO] setting privileges on built-in objects ... ok
[INFO] creating information schema ...
[INFO] FATAL:  could not access status of transaction 0
[INFO] DETAIL:  Could not open file "pg_notify/0000": Permission denied.
[INFO] child process exited with exit code 1
[INFO] initdb: removing data directory "C:/Users/Carlos Miranda/git/jcabi-jdbc/target/data"
[INFO]
[INFO] --- postgresql-maven-plugin:0.2-SNAPSHOT:start (init-db) @ jcabi-jdbc ---
[INFO] Startig PostgreSQL
```

**Comment by dmarkov** [comment]
@cyberone the task is your hands for the last 13 days.. keep in mind that if it's not closed in the next 16 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. added -30 to your rating, now it is equal to [-280](http://www.netbout.com/b/35076?open=rating)

**Comment by yegor256** [comment]
@dmarkov assign someone else pls

**Comment by dmarkov** [comment]
> @dmarkov assign someone else pls

@yegor256 no problem, I'll try to find somebody else

**Comment by dmarkov** [comment]
@jenya This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment]
@dpisarenko it's yours, please go ahead

**Comment by dpisarenko** [comment]
@dmarkov Please assign the task to someone else. I ran `mvn clean install -Pqulice` under Windows 7 several times and could not reproduce the error.

**Comment by dmarkov** [comment]
> @dmarkov Please assign the task to someone else. I ran `mvn clean install -Pqulice` under Windows 7 several times and could not reproduce the error.

@dpisarenko right, I will find someone else, no problem

**Comment by dmarkov** [comment]
@maurezen please go ahead with this task, it's yours

**Comment by maurezen** [comment]
@carlosmiranda aren't you building under the user with admin rights by any chance? the tests (and postgres instance as well) are ran under the same user, and you can't run postgres under admin.

@dmarkov pull request #38

**Comment by carlosmiranda** [comment]
@maurezen Yes I am using an administrator account to run. The problem is not that it fails per se but it hangs intermittently.

**Comment by maurezen** [comment]
@carlosmiranda and that's what is fixed in my pull request.

**Comment by maurezen** [comment]
@carlosmiranda pull request #38 merged, please close the issue.

**Comment by carlosmiranda** [comment]
Thanks!

**Comment by maurezen** [comment]
@dmarkov the task has been closed 6 days ago.

**Comment by maurezen** [comment]
@yegor256 see? the task closed and the task paid are unfortunately not the same.

**Comment by dmarkov** [comment]
@maurezen Thank you, I've added **30 mins** to your account in payment/transaction "`51288540`"; +30 added to your rating, at the moment it is: [+1005](http://www.netbout.com/b/35102?open=rating)
