### ISSUE TITLE
Documentation examples on transaction management contains invalid code

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-jdbc#23]
In our documentation page http://jdbc.jcabi.com/example-transaction.html, we have the following example, which contains some invalid statements:

```java
public class Main {
  public static void main(String[] args) {
    new JdbcSession(source)
      .autocommit(false)
      .sql("START TRANSACTION")
      .update() // Will not compile!
      .sql("DELETE FROM employee WHERE name = ?")
      .set("Jeff Lebowski")
      .update() // Ditto.
      .sql("INSERT INTO employee VALUES (?)")
      .set("Walter Sobchak")
      .insert(Outcome.VOID) // Neither will this.
      .commit();
  }
}
```

This is wrong because the method `update` and `insert` have signatures `T update(Outcome<T>)` and `T insert(Outcome<T>)`. We should be referring to the `execute()` method instead, like so:

```java
public class Main {
  public static void main(String[] args) {
    new JdbcSession(source)
      .autocommit(false)
      .sql("START TRANSACTION")
      .execute() // Now this will compile!
      .sql("DELETE FROM employee WHERE name = ?")
      .set("Jeff Lebowski")
      .execute() // Change it here, too
      .sql("INSERT INTO employee VALUES (?)")
      .set("Walter Sobchak")
      .execute() // And here.
      .commit();
  }
}
```

**Comment by darkled** [comment]
@carlosmiranda @dmarkov please, pay your attention, that PR is sent, but it's acceptance is blocked by #33

**Comment by yegor256** [comment]
@dmarkov we're waiting for #33

**Comment by dmarkov** [comment]
> @dmarkov we're waiting for #33

@yegor256 sure, let's wait for #33

**Comment by dmarkov** [comment]
I think we can continue, impediment #33 is closed

**Comment by darkled** [comment]
@carlosmiranda should be fixed within PR #32, please, check it and close the issue if it is done.

**Comment by carlosmiranda** [comment]
@darkled Indeed it's fixed, thank you. Closing now.

**Comment by dmarkov** [comment]
@darkled thank you, added **30 mins** to your acc, payment num is `50573737`... +30 added to your rating, current score is: [+285](http://www.netbout.com/b/35091?open=rating)
