### ISSUE TITLE
Build failed because postgresql-maven-plugin 0.2-SNAPSHOT is not available

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-jdbc#33]
we need to upgrade the project to use plugin version 0.2 (not a snapshot)
```
<groupId>com.github.adrianboimvaser</groupId>
<artifactId>postgresql-maven-plugin</artifactId>
<version>0.2</version>
```

**Comment by dmarkov** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by dmarkov** [comment]
@adko-pl it's yours, please go ahead

**Comment by dmarkov** [comment]
@longtimeago thank you for reporting this, I added 15 mins to your acc, transaction `49905252`

**Comment by longtimeago** [comment]
@adko-pl any news?

**Comment by adko-pl** [comment]
@longtimeago delivered in https://github.com/jcabi/jcabi-jdbc/pull/35

**Comment by longtimeago** [comment]
@adko-pl thanks!

**Comment by dmarkov** [comment]
@adko-pl **30 mins** was added to your account, many thanks for your contribution!. +30 added to your rating, current score is: +95
