### ISSUE TITLE
Build failed on windows with lots of EOL violations

### ISSUE THREAD

**Issue by YamStranger** [jcabi/jcabi-jdbc#43]
@dmarkov Looks like we need to add .gitattributes to force EOL of the repo.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by YamStranger** [comment]
@yegor256. It is known problem, qulice fail if default system EOF not like in linux. So we need add .attributes to repository for force setting Unix-like end of line to git repository. 
AppVeyor use linux like EOF. 
This repository will not build successfully if you install git, install maven, clone repo and just build. 
Here is some examples of same problem at different repositories:
This is issue same as here https://github.com/jcabi/jcabi-maven-skin/issues/24 (build failed on Windows)
same is here https://github.com/yegor256/takes/issues/148
fix mast be like here https://github.com/jcabi/jcabi-aether/pull/59/files#diff-fc723d30b02a4cca7a534518111c1a66

**Comment by yegor256** [comment]
@YamStranger fixed in https://github.com/jcabi/jcabi-jdbc/commit/6939bb54354c2c858f44551d4f8137fdf4c0ae6b
