### ISSUE TITLE
Execute stored procedures with output parameter

### ISSUE THREAD

**Issue by DavDavid** [jcabi/jcabi-jdbc#51]
Is it possible execute a stored procedure that has output parameters? I have tried:

```
String result = new JdbcSession(datasource)
  .sql("call procedure('paramIn', 'paramOut')")
  .update(new SingleOutcome<>(String.class)
;
```

but doesn't work. It returns a java.sql.SQLException: ORA-06577.

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@DavDavid we don't support that now. we should create an instance of `CallableStatement` and then do this:

```
stmt.registerOutParameter(1, Types.VARCHAR);
```

I don't know how exactly to extend our library to support that... Let's think

**Comment by yegor256** [comment]
@DavDavid maybe you have a suggestion?

**Comment by dmarkov** [comment]
@amihaiemil please help, the task is yours

**Comment by amihaiemil** [comment]
@DavDavid  Can you try to see if this works? 
```
String result = new JdbcSession(datasource)
  .sql("call procedure('paramIn', 'paramOut')")
  .prepare(
      new Preparation() {
          @Override
	      public void prepare(PreparedStatement stmt) throws SQLException {
              CallableStatement cstmt = (CallableStatement) stmt;
	          cstmt.registerOutParameter(1, Types.VARCHAR);					
          }
      }
  )
  .update(new SingleOutcome<>(String.class);
```

**Comment by DavDavid** [comment]
It gives me a ClassCastException in CallableStatement line:
java.lang.ClassCastException: oracle.jdbc.driver.OraclePreparedStatementWrapper cannot be cast to java.sql.CallableStatement
	at com.simula.Simulation$1.prepare(Simulation.java:167)
	at com.jcabi.jdbc.JdbcSession.configure(JdbcSession.java:440)
	at com.jcabi.jdbc.JdbcSession.run(JdbcSession.java:377)
	at com.jcabi.jdbc.JdbcSession.update_aroundBody14(JdbcSession.java:304)
	at com.jcabi.jdbc.JdbcSession$AjcClosure15.run(JdbcSession.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.jdbc.JdbcSession.update(JdbcSession.java:304)
	at com.simula.Simulation.main(Simulation.java:161)

**Comment by amihaiemil** [comment]
@DavDavid right, i'm going to make an implementation for this requirement, this weekend :D

**Comment by amihaiemil** [comment]
@dmarkov I created PR #53 for this issue.

**Comment by amihaiemil** [comment]
@DavDavid I created a PR for this. It will take a couple of days until it is reviewed and merged. Please don't switch off notifications from this issue, as you will have to close it in the end (that's how we work here). Many thanks!

**Comment by dmarkov** [comment]
> @dmarkov I created PR #53 for this issue.

@amihaiemil thanks for that

**Comment by amihaiemil** [comment]
@dmarkov I need more time

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@amihaiemil yes, take your time, thanks for letting me know

**Comment by amihaiemil** [comment]
@DavDavid the pr was finally merged. See details on how to use the new functionality in its description.

Can you close this ticket?

**Comment by DavDavid** [comment]
Ok, thanks very much

**Comment by dmarkov** [comment]
@davdavid the code made here contains a puzzle `51-55acd5db`/#56, which will be resolved soon

**Comment by dmarkov** [comment]
@amihaiemil thanks, I just added **30 mins** to your account, payment `AP-2R818475C7709490E`, 2547 hours and 5 mins spent. +30 added to your rating, at the moment it is: [+1039](http://www.netbout.com/b/36402?open=rating)

**Comment by dmarkov** [comment]
@davdavid the last puzzle `51-55acd5db`/#56 originated from here solved

**Comment by 0pdd** [comment]
@DavDavid the puzzle [#unknown]() is still not solved.
