### ISSUE TITLE
JdbcSession shouldn't close the connection it is given

### ISSUE THREAD

**Issue by andrejserafim** [jcabi/jcabi-jdbc#54]
`JdbcSession` has 2 constructors - from a `DataSource` and a `Connection`. When it's dealing with data sources, it's getting it's own connections and closing them, but if it's given a connection, it's not it's job to close it - it is given to it.

The code, which created the connection should look after it. It may be needed for subsequent calls or whatnot.

Right now it closes a connection regardless of what constructor is used after a first execution.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@andrejserafim totally agree, it's a bug, thanks for pointing out

**Comment by dmarkov** [comment]
@amihaiemil the task is yours (budget is 30 mins)

**Comment by amihaiemil** [comment]
@andrejserafim You can disable the autocommit/close by calling ``.autocommit(false)`` before anything else.

Look how the tests are written [here](https://github.com/jcabi/jcabi-jdbc/blob/master/src/test/java/com/jcabi/jdbc/JdbcSessionITCase.java)

Isn't that good for you, or you think we should do the other way around? autocommit false by default, and true only if you specify it?

**Comment by amihaiemil** [comment]
@andrejserafim and in the [JdbcSession.run()](https://github.com/jcabi/jcabi-jdbc/blob/master/src/main/java/com/jcabi/jdbc/JdbcSession.java#L398) method the autocommit flag is set on the connection, and lastly, in the finally block, it is disconnected only if ``this.auto==true``

![image](https://cloud.githubusercontent.com/assets/6305156/20517409/99a1610e-b0a3-11e6-9abb-0f7f661b91ac.png)

**Comment by andrejserafim** [comment]
@amihaiemil sorry boss, but the state of autocommit is irrelevant here. I know that's the current behaviour, but that's not what the issue is about.

**Comment by amihaiemil** [comment]
@andrejserafim Can you ellaborate just a little more, then? I'm not sure I see it :D

**Comment by andrejserafim** [comment]
@amihaiemil it's about instance ownership. A connection `JdbcSession` creates it's free to do whatever it wants with. A connection it is given it better not touch. An analogy would be if you give a list to `System.out.println(list)` like so. Would you expect for it mess with the list? Same deal here - use the connection `JdbcSession` is given to run sql, but don't close it. An alternative is removing that constructor.

**Comment by amihaiemil** [comment]
@andrejserafim I understand the concept that a blackbox should not alter resources I provide it - that perfectly makes sense, but this JdbcSession offers the alternative to not close the connection, if you specify ``.autocommit(false)``

I was saying that, as far as I can see, that stuff works fine. Did you notice a bug in that mechanism, that I did not notice? Or you simply think that mechanism is not ok at all? 

I think it's nothing wrong to alter a resource, as long as the client knows about it and has the option to disable the altering.

**Comment by amihaiemil** [comment]
@andrejserafim I will make a PR with the removed ctor - let me know if you reconsider in the meantime :D

**Comment by andrejserafim** [comment]
@amihaiemil think about when I would want to use autocommit(false) and when I would want to use `JdbcSession`. Are those 2 sets of use cases perfectly aligned? I don't think so. Since one is about transaction management and the other about running arbitrary sql.

**Comment by amihaiemil** [comment]
@andrejserafim Yes they are alligned - I'm talking about method ``JdbcSession.autocommit(boolean)``, which sets the auto flag and returns the instance. 

So if you expect your connection to be automatically commited, you would do
```
new JdbcSession(connection)
   .sql("SQL STATEMENT")
   .execute();
```
and if you don't want your connection commited/closed, you do
```
new JdbcSession(connection)
   .autocommit(false)
   .sql("SQL STATEMENT")
   .execute()
   //... possibly other sql calls...
  .sql("OTHER SQL STATEMENT")
  .execute()
  .commit();
```

**Comment by andrejserafim** [comment]
@amihaiemil counter example:

```java
new JdbcSession(connection)
   .sql("SQL STATEMENT")
   .execute();
new JdbcSession(connection)
   .sql("SQL STATEMENT 2")
   .execute();
```

what will happen? The second statement will throw since the connection is already closed. Yet all I did was manage transactions. I'm guessing that's because `JdbcSession` is usually used in connection pool contexts. Not with a single connection.

**Comment by amihaiemil** [comment]
@andrejserafim Now I see your point :) 

Yes, from this autocommit point of view, the ``JdbcSession`` class is design to chain method calls on the same reference, or use the same reference everywhere...

So yes, in your example it will fail :D
Then, rather than removing the ctor, wouldn't it be better to reverse the mechanism? autocommit false by default and true only if you specify it? This way, your example would work and this

```
new JdbcSession(connection)
   .autocommit(true)
   .sql("SQL STATEMENT")
   .execute();
new JdbcSession(connection)
   .sql("SQL STATEMENT 2")
   .execute();
```
would fail, but it would be expected, the client called ``autocommit(true)``

**Comment by amihaiemil** [comment]
@andrejserafim Actually, on second thought, I will remove the ctor - it's less damage to backwards compatibiliy :)

**Comment by amihaiemil** [comment]
@andrejserafim done, you can check the PR - please don't turn off notifications from this issue. In the end, when the PR is merged, you should be the one to close this ticket! Thanks! :)

**Comment by amihaiemil** [comment]
@andrejserafim PR was merged; can you close this? :D

**Comment by andrejserafim** [comment]
@amihaiemil thanks!

**Comment by dmarkov** [comment]
@amihaiemil Thanks a lot, I just topped your account for **45 mins**, transaction ID `AP-23T3163322913823G`, total time was 26 hours and 5 mins; the bonus for fast delivery (m=1565); +45 to your rating, your total score is [+1054](http://www.netbout.com/b/36402?open=rating)
