### ISSUE TITLE
How to use IN condition

### ISSUE THREAD

**Issue by maksimu** [jcabi/jcabi-jdbc#60]
I have a query where I need to provide a list of items in WHERE condition and I use IN here. How would one go about that?

Here is the example sql:

```sql
SELECT id, name, title
FROM doctorTbl
WHERE id IN (1, 3, 56, 70)
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by maksimu** [comment]
My solution was following:

```java
        for( int i = 0 ; i < doctorList.size(); i++ ) {
            builder.append("?,");
        }

        String inSection = builder.deleteCharAt( builder.length() -1 ).toString(); // rem last comma

        String sql = "SELECT id, name, title FROM doctorTbl WHERE id IN (?)";
        sql = sql.replace("id IN (?)", "id IN (" + questionMarks + ")");
        JdbcSession selectJdbcSession = new JdbcSession(dataSource).sql(sql);
        for(Long cId : usersConversationsList) {
            selectJdbcSession.set(cId);  // id IN (?)
        }

       ...
```

Not that clean as I was hopping it to be.

**Comment by yegor256** [comment]
@maksimu I would just generate the SQL like `in (?, ?, ?, ...)` (as many as you need) and then use `.set*()` methods to provide values.

**Comment by maksimu** [comment]
That's exactly what I did. Good to hear that I'm not the only one who thinks this way

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-jdbc#60` was not in scope
