### ISSUE TITLE
jcabi-jdbc requires aspectj

### ISSUE THREAD

**Issue by nshusa** [jcabi/jcabi-jdbc#63]
For my mysql project I can't use jcabi-jdbc as it requires aspectj. For my postgres project I don't get this issue? Why am I getting this? I added jcabi-jdbc-0.16 to my classpath.

For the mysql project I'm not using a dependency manger such as maven or gradle I'm adding it straight to the classpath since the people I'm working with refuse to use one.

For my postgres project I use gradle and have no issues at all with this library.

![IMAGE](https://i.imgur.com/ce7xY5d.png)

![IMAGE](https://i.imgur.com/TMkncXW.png)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by yegor256** [comment]
@nshusa try version 0.17 pleae

**Comment by nshusa** [comment]
@yegor256 Ok, I'll try it later today when I get home.

**Comment by nshusa** [comment]
@yegor256 Apologize for the massive delay but just tried it on version 0.17.2 and this still happens.

!(https://i.imgur.com/zh4qS8I.png)[https://i.imgur.com/zh4qS8I.png]

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#63` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
