### ISSUE TITLE
Setting NULL value in INSERT statement doesn't work

### ISSUE THREAD

**Issue by piotrkot** [jcabi/jcabi-jdbc#65]
Null arguments are set to String value instead of null.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by piotrkot** [comment]
I will provide a fix, if you don't mind :)

**Comment by yegor256** [comment]
@piotrkot fixed and released 0.17.1

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#65` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
