### ISSUE TITLE
Couldn't suppress checkstyle's CyclomaticComplexity warning

### ISSUE THREAD

**Issue by verkhovin** [jcabi/jcabi-jdbc#67]
Hello! I am trying to use this lib in my in my pet project with Postgresql. 
I need to store some double values, but the lib does not support Double type at this moment so I decided to extend the lib.
I've added one more if-statement into prepare() method of PrepareArgs class:

```
    @Override
    @SuppressWarnings(
        {
            "PMD.CyclomaticComplexity", "PMD.StdCyclomaticComplexity",
            "PMD.ModifiedCyclomaticComplexity"
        }
    )
    public void prepare(final PreparedStatement stmt) throws SQLException {
        int pos = 1;
        for (final Object arg : this.args) {
            if (arg == null) {
                stmt.setNull(pos, Types.NULL);
            } else if (arg instanceof Long) {
                stmt.setLong(pos, Long.class.cast(arg));
            } else if (arg instanceof Boolean) {
                stmt.setBoolean(pos, Boolean.class.cast(arg));
            } else if (arg instanceof Date) {
                stmt.setDate(pos, Date.class.cast(arg));
            } else if (arg instanceof Integer) {
                stmt.setInt(pos, Integer.class.cast(arg));
            } else if (arg instanceof Utc) {
                Utc.class.cast(arg).setTimestamp(stmt, pos);
            } else if (arg instanceof Float) {
                stmt.setFloat(pos, Float.class.cast(arg));
            } else if (arg instanceof  Double) { // <--- this one
                stmt.setDouble(pos, Double.class.cast(arg));
            } else if (arg instanceof byte[]) {
                stmt.setBytes(pos, byte[].class.cast(arg));
            } else {
                stmt.setString(pos, arg.toString());
            }
            ++pos;
        }
    }
```

CyclomaticComplexity warning seems to suppressed here but running `maven clean install -Pqulice` failed with this message:

> [INFO] Checkstyle: E:\dev\Repositories\jcabi-jdbc\src\main\java\com\jcabi\jdbc\PrepareArgs.java[61]: Cyclomatic Complexity is 11 (max allowed is 10). (CyclomaticComplexityCheck)

I also tried `// @checkstyle CyclomaticComplexity (26 lines)` at the start of the method but it doesn't work too. Where am i wrong?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@verkhovin[/z](https://www.0crat.com/u/verkhovin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@verkhovin you should suppress the Checkstyle warning, not PMD. Also, make sure you cover enough lines in your suppression instruction. Maybe 26 is just not enough.

**Comment by 0crat** [comment]
This job is not in scope
