### ISSUE TITLE
Setting value in insert using Object doesn't work

### ISSUE THREAD

**Issue by piotrkot** [jcabi/jcabi-jdbc#68]
It's not possible to set Object value in PreparedStatement. Giving the option to set Object simplifies the `PrepareArgs.prepare` method, too.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by piotrkot** [comment]
@0crat commands

**Comment by piotrkot** [comment]
@0crat hello

**Comment by piotrkot** [comment]
@0crat Assign to me. I will create a PR

**Comment by 0crat** [comment]
You must be invited in order to do that, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by piotrkot** [comment]
By the way, without the way to setObject I cannot use Java Date and Time classes in PostgreSQL, even though they are [supported](https://jdbc.postgresql.org/documentation/head/8-date-time.html) by the driver.

**Comment by piotrkot** [comment]
Fixed.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#68` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by piotrkot** [comment]
I don't know if it makes a difference, but I reopen the issue as the fixed version hasn't been released yet.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by yegor256** [comment]
@piotrkot it's released, thanks

**Comment by piotrkot** [comment]
@yegor256 thank you

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@1c1f6633-0ff2-4c0c-98d3-ae51175b909b, thread: AsyncProc-2
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:jcabi/jcabi-jdbc#68] declared for identity constraint of element "blanks".
```

[0.40.1](https://github.com/zerocracy/farm): CID: [c6573621-dffa-47b2-84af-6b125eef32e7](https://www.0crat.com/footprint/C3RUBL5H9/c6573621-dffa-47b2-84af-6b125eef32e7), Type: "Close job"

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#68` is not assigned, can't get performer
