### ISSUE TITLE
No possibility to rollback transaction

### ISSUE THREAD

**Issue by golszewski86** [jcabi/jcabi-jdbc#71]
The autocommit=false feature allows to execute several SQL commands in one transaction. The documentation says:

> The last statement should be a call to commit(), which translates to the native transaction commit SQL statement.
https://jdbc.jcabi.com/example-transaction.html

And that's fine when I want to *commit* my transaction, but sometimes I want to *rollback* it, e.g.:
```
final JdbcSession session = new JdbcSession(source);
try {
   long inserted = session.sql("some sql here").insert(Outcome.LAST_INSERT_ID);
   // some logic here, maybe calls to external services
   session.sql("some other sql").execute().commit();
} catch (SomeBusinessException ex) {
   session.rollback(); // There is no such method!
}
```
So, sometimes I want to rollback my transaction basing on business logic.

It is also possible that some exception occurs before `session.commit()` and this code will not be executed. In this case database transaction remains active (at least in PostgreSQL).

Thus there should be a rollback() method in JdbcSession class along with commit(). The java.sql.Connection class has a rollback() method which should be used.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@golszewski86 thanks for your contribution. I released the version `0.17.3` in https://github.com/jcabi/jcabi-jdbc/pull/72

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#71` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
