### ISSUE TITLE
Can't specify username and password for connection

### ISSUE THREAD

**Issue by scristalli** [jcabi/jcabi-jdbc#73]
`JdbcSession` uses a plain `getConnection()`, without offering the possibility of specifying username and password. I must specify them to connect to a particular database, and I can't use jcabi-jdbc with this problem.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@scristalli[/z](https://www.0crat.com/u/scristalli) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by Glusk** [comment]
> `JdbcSession` uses a plain `getConnection()`, without offering the possibility of specifying username and password. I must specify them to connect to a particular database, and I can't use jcabi-jdbc with this problem.

You can do that by configuring your `DataSource`. For example, this would be a basic example using the MySQL Connector/J:

``` java
// String username = "user";
// String password = "123";
MysqlDataSource ds = new MysqlDataSource();
ds.setUser(username);
ds.setPassword(password);
ds.setURL("jdbc:mysql://localhost");
ds.setPort(3306);
ds.setDatabaseName("MyAwesomeDatabase");
// ...
new JdbcSession(ds);
```

**Comment by andreoss** [comment]
@scristalli  It appears that problem was resolved.
https://github.com/g4s8/ghman/issues/52#issuecomment-511585439
