### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by Glusk2** [jcabi/jcabi-jdbc#74]
The travis build is failing (branch `master`, commit 5db4123):
https://travis-ci.org/jcabi/jcabi-jdbc/builds/602315844

Error message:
``` code
Expected feature release number in range of 9 to 14, but got: 8
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@glusk2[/z](https://www.0crat.com/u/glusk2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@Glusk2 it's clean now

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#74` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
