### ISSUE TITLE
Missing documentation - UUID data type is not supported

### ISSUE THREAD

**Issue by pluresideas** [jcabi/jcabi-jdbc#76]
UUID data type is not supported by jcabi-jdbc according to the discussion [here.](https://www.yegor256.com/2014/08/18/fluent-jdbc-decorator.html)

Would it be a good idea to state this restriction in the project's README.md?

This restriction, if not known ahead of time, can be costly for some projects hence I would prefer that it is somewhere visibly documented.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@pluresideas[/z](https://www.0crat.com/u/pluresideas) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@pluresideas merged, thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#76` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
