### ISSUE TITLE
High cyclomatic complexity and code duplication

### ISSUE THREAD

**Issue by Glusk** [jcabi/jcabi-jdbc#79]
Some classes have high cyclomatic complexity and the same code is duplicated among several classes.

### Examples:
In value-setting classes:
- https://github.com/jcabi/jcabi-jdbc/blob/fda07ca7bbd875d246a410a199e9c770231e82b6/src/main/java/com/jcabi/jdbc/PrepareArgs.java#L61-L93

In value-retrieving classes:
- https://github.com/jcabi/jcabi-jdbc/blob/b4e2298d0287b4c7c35ff389a3c092dd61cf006c/src/main/java/com/jcabi/jdbc/SingleOutcome.java#L133-L163
- https://github.com/jcabi/jcabi-jdbc/blob/b4e2298d0287b4c7c35ff389a3c092dd61cf006c/src/main/java/com/jcabi/jdbc/ColumnOutcome.java#L104-L134

---

Perhaps instead of filtering the arguments in jcabi-jdbc one could let the JDBC driver do the work by utilizing the ResultSet's:
[`<T> T getObject(int columnIndex, Class<T> type) throws SQLException`](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#getObject-int-java.lang.Class-)
and PreparedStatement's:
[`void setObject(int parameterIndex, Object x) throws SQLException`](https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setObject-int-java.lang.Object-)

In doing so, features mentioned in #57 and #76 would work automatically.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@glusk2[/z](https://www.0crat.com/u/glusk2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by andreoss** [comment]
@Glusk Done in #99

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#79` is not assigned, can't get performer

**Comment by Glusk** [comment]
@andreoss

I don't think I like this "mapping" solution.

Before, valid parameters were more visible in that big **`if`** clause. If I wanted to contribute to the library, I knew exactly where to edit the code to add or remove a certain type. Now, all I see is this `mapping`, and I have to scroll up, look for a declaration of a field, look for the file in which `Mapping` is defined…

In hope of achieving brevity (which is debatable, as 38b631b has more additions than deletions), you have sacrificed clarity.

What was wrong with my idea?

**Comment by andreoss** [comment]
@Glusk 
>What was wrong with my idea?
Nothing, besides it's driver specific. But using a more generic API wouldn't solve the code duplication problem completely (only shrink the `if` block a bit). 
Some kind of object should be passed to `SingleOutcome` and `CollectionOutcome` to represent mapping, hence `Mapping`.
I don't think that code discoverability suffered a lot, you can find the familiar dispatch table here https://github.com/jcabi/jcabi-jdbc/commit/38b631bd60775879d85042cfee98432e36f6173c#diff-1405f17549265d5569e5c0fe4dc75e6e6eef230eaafbf65399abf1845cb5671bR66
