### ISSUE TITLE
Storing JdbcSession argument in CopyOnWriteArrayList is suboptimal

### ISSUE THREAD

**Issue by golszewski86** [jcabi/jcabi-jdbc#80]
JdbcSession stores all the arguments in CopyOnWriteArrayList which implies copying the whole list every time an argument is added. In most cases it doesn't make any difference compared to mutable list like ArrayList or LinkedList, but when you have to add thousands of arguments it causes a significant overhead.

According to javadoc the CopyOnWriteArrayList "is ordinarily too costly, but may be more efficient than alternatives when traversal operations vastly outnumber mutations, and is useful when you cannot or don't want to synchronize traversals, yet need to preclude interference among concurrent threads".

Obviously in case of JdbcSession  traversal operations don't outnumber mutations and accessing this (mutable) object from multiple threads doesn't make any sense.

Can we get rid of CopyOnWriteArrayList in the sake of performance when it comes to really huge arguments' lists?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.2`

**Comment by yegor256** [comment]
@golszewski86 it's fixed in 0.18.2, per your suggestion
