### ISSUE TITLE
Update parent to 1.25.2

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-jdbc#81]
Bump parent to ~~[1.25.2](https://search.maven.org/artifact/com.jcabi/jcabi/1.25.2/jar)~~ 1.27.0

**Comment by 0pdd** [comment]
@andreoss the puzzle [#85](https://github.com/jcabi/jcabi-jdbc/issues/85) is still not solved.

**Comment by yegor256** [comment]
@andreoss upgrade it to `1.27.0` instead

**Comment by andreoss** [comment]
@rultor release, tag=`0.17.5`

**Comment by 0pdd** [comment]
@andreoss the only puzzle [#85](https://github.com/jcabi/jcabi-jdbc/issues/85) is solved here.
